### ISSUE TITLE
No commands work after enabling this plugin

### ISSUE THREAD

**Issue by 143mailliw** [streamer45/mattermost-plugin-voice#1]
When I enable this plugin, no commands respond to using them. There is no obvious errors in the console log, and disabling this plugin fixed other plugins and Mattermost's commands.

**Comment by streamer45** [comment]
@143mailliw thank you for reporting this bug.
430a1c9 should fix this.

**Comment by 143mailliw** [comment]
I can't compile it, it throws error 33 at line 105 every time.

**Comment by streamer45** [comment]
Should be fixed now. If it still fails please post a full log of compilation.

**Comment by 143mailliw** [comment]
```touch webapp/.npminstall
mkdir -p dist && \
mkdir -p public && \
cd dist && \
curl -L -o ""mp3enc-wasm-"0.1.6"".tar.gz" -C - "https://github.com/streamer45/mp3rec-wasm/releases/download/v"0.1.6"/"mp3enc-wasm-"0.1.6"".tar.gz" 2> /dev/null && \
cd ../public && \
tar xf ../dist/"mp3enc-wasm-"0.1.6"".tar.gz 2> /dev/null && \
mv "mp3enc-wasm-"0.1.6""/* . && \
mv recorder.js ../webapp/src/client/ && \
rm -rf "mp3enc-wasm-"0.1.6""
Makefile:105: recipe for target 'mp3-wasm' failed
make: *** [mp3-wasm] Error 33```

**Comment by streamer45** [comment]
I cannot seem to reproduce that. Can you share your OS type and version?
In the meantime I have [released](https://github.com/streamer45/mattermost-plugin-voice/releases/tag/v0.1.1) a new compiled version of the plugin.

**Comment by 143mailliw** [comment]
Ubuntu 18.04.3
Node: 8.10.0
Go: 1.10.4
GNU Make: 4.1

**Comment by 143mailliw** [comment]
I'll try on Arch when I get home, I'm compiling on my server right now.

**Comment by 143mailliw** [comment]
The fix works, by the way, so I'm going to close this issue and start a new one for the compiling issue.
