### ISSUE TITLE
Send voice message in the mobile version !!!

### ISSUE THREAD

**Issue by majidit** [streamer45/mattermost-plugin-voice#27]
Hello to all dear friends
Why can't you send a voice message in the mobile version?
This is a basic need and our team users have requested it a lot
@streamer45

**Comment by streamer45** [comment]
Hi @majidit,

as explained in the README, this is [a limitation](https://developers.mattermost.com/extend/plugins/mobile/) of the MM plugin framework so nothing that can be done on this side of things.
There is work in the planning to add mobile support to plugins but until that's the case there isn't much we can do.
