### ISSUE TITLE
Not working with Mattermost Android client

### ISSUE THREAD

**Issue by rezart** [streamer45/mattermost-plugin-voice#3]
I was unable to record new recordings from mobile or view posted voice recordings. Is this expected? I am currently using the Mattermost Android client.

**Comment by streamer45** [comment]
Unfortunately it is expected. Mattermost does [not yet support](https://developers.mattermost.com/extend/plugins/mobile/) client side plugins on mobile.

The plugin itself should work on modern mobile clients but on the webapp only and not yet from a native client. Hopefully this will change soon as I understand the need for an integration like this to  fully support a mobile environment.

**Comment by streamer45** [comment]
Closing for now since there's not much we can do.
