### ISSUE TITLE
Support of MM server version >7 ?

### ISSUE THREAD

**Issue by thopico** [streamer45/mattermost-plugin-voice#45]
Hi,

Since I've upgraded my MM server to 7.0.0, voice plugin doesn't seem to work anymore. I'm running plugin version 0.2.2.

The only logs I was able to retrieve are :
```
{"timestamp":"2022-07-06 09:42:09.212 +02:00","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:412","tag_value":"sysconsole_write_*_read"}
{"timestamp":"2022-07-06 09:42:09.283 +02:00","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"com.mattermost.voice","wrapped_extras":"path/mattermost/plugins/com.mattermost.voice/server/dist/plugin-linux-amd64pid832"}
```
but I don't even know if the first log is related to this plugin.

Might it be a version compatibility issue? Do you have any clue to help me debugging this?

Thanks in advance

**Comment by streamer45** [comment]
Hey @thopico, I think we'd need to update some dependencies and build a new release. I'll have a look at this later this week, should be trivial to fix.

**Comment by streamer45** [comment]
I had a look at this and can run the plugin just fine on 7+ versions so we may be looking at something else here. I'd suggest to enable DEBUG level logging and see if we can get more info.

**Comment by thopico** [comment]
Hi @streamer45. Since...

1. I can't reproduce the original behavior (without having changed anything on my instance though)
2. There is a remaining React error with a user, but it's different and seems related to #21 :
```
Uncaught (in promise) Error: Recorder is not initialized
```
3. You've just built a new release

... I will close the issue now.
Thank you!
