### ISSUE TITLE
Record not show on upload icon

### ISSUE THREAD

**Issue by yusufinthehouse** [streamer45/mattermost-plugin-voice#48]
I have installed the plugin on my Mattermost 7.
It can work if I used `/voice` command. But on upload icon, it only show blank menu

<img width="246" alt="Screen Shot 2022-08-02 at 15 52 25" src="https://user-images.githubusercontent.com/3617155/182334619-89337800-61c9-41d5-bc7a-d049ca899dd9.png">

**Comment by streamer45** [comment]
@yusufinthehouse What Mattermost version are you running?

**Comment by yusufinthehouse** [comment]
> @yusufinthehouse What Mattermost version are you running?

@streamer45 mattermost version 7.0.0

**Comment by streamer45** [comment]
This was fixed in 7.0.1 I believe, upgrading should work. See https://docs.mattermost.com/install/self-managed-changelog.html#release-v7-0-major-release for more details.

**Comment by yusufinthehouse** [comment]
I see, upgrading works. Thanks for your help @streamer45
