### ISSUE TITLE
Not working with mobile app

### ISSUE THREAD

**Issue by aminzafarghandi** [streamer45/mattermost-plugin-voice#7]
Dear
do you have any estimate for your new release to include voice message on mobile app ?

**Comment by AnonStar** [comment]
We also only can use this plugin when it's working with the mobile app. Unfortunately as I read in another issue the mattermost mobile app isn't working with any plugin at the moment.

**Comment by streamer45** [comment]
Correct, as explained in https://github.com/streamer45/mattermost-plugin-voice/issues/3#issuecomment-521544719 there's currently no support for mobile plugins.
