### ISSUE TITLE
Feature request: Would it be easy to make the Cancel and Send link box and font larger?

### ISSUE THREAD

**Issue by kaksikanaa** [streamer45/mattermost-plugin-voice#8]
Hi!
This is wonderful plugin, many thanks for this!

Would it be possible to make the Cancel and Send box and those strings in 2x or 3x size? They are a bit of a struggle to hit while in mobile and driving a car you know... and it would be helpful in the desktop app too. Thanks!

**Comment by streamer45** [comment]
@kaksikanaa 
I apologize for the quite late reply. 
Thank you for your feedback and proposal. Unfortunately I haven't had much time to invest into this plugin.  I'll get back to you if I manage to address this request.
In the meantime, [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) are more than welcome if anyone is willing to contribute.

**Comment by streamer45** [comment]
I've slightly increased the font-size in the [latest](https://github.com/streamer45/mattermost-plugin-voice/releases) release. Closing.
